apiVersion: apps/v1
kind: Deployment
metadata:
  name: openzipkin-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openzipkin-service
  template:
    metadata:
      labels:
        app: openzipkin-service
    spec:
      containers:
        - name: openzipkin-service
          image: openzipkin/zipkin
          resources:
            requests:
              memory: "300Mi"
          ports:
            - containerPort: 9411
