apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: said160/ms-api-gateway-service:0.0.1-SNAPSHOT
          resources:
            requests:
              memory: "700Mi"
          ports:
            - containerPort: 8765
          env:
            - name: EUREKA.CLIENT.SERVICEURL.DEFAULTZONE
              value: "http://naming-registry-service:8761/eureka"
            - name: MANAGEMENT.ZIPKIN.TRACING.ENDPOINT
              value: "http://zipkin-service:9411/api/v2/spans"
